### ISSUE TITLE
Does not build today - implicit dependency on SB-POSIX

### ISSUE THREAD

**Issue by quicklisp** [ghollisjr/cl-ana#10]
http://report.quicklisp.org/2015-12-07/failure-report/cl-ana.html#cl-ana has a full log.

It looks like cl-ana references SB-POSIX symbols without explicitly depending on sb-posix.

**Comment by ghollisjr** [comment]
Should be fixed now, can you confirm?

**Comment by quicklisp** [comment]
No, it's not fixed. To fix it, you have to add SB-POSIX to the :depends-on list in the system file, or REQUIRE it early enough, or something similar.

To test a fix, try loading cl-ana from a bare SBCL repl without slime or anything else loaded. That will make SB-POSIX dependency issues stand out.

**Comment by ghollisjr** [comment]
I still can't reproduce the error but I've added a conditional dependency to ensure that sb-posix is required for SBCL.

**Comment by quicklisp** [comment]
Thanks. I've gotten past SB-POSIX, but there's a new problem.

It seems like (spawn-gnuplot-session) is breaking on my system, and it happens unconditionally at load time. Would it be possible to defer spawn-gnuplot-session to runtime?

Log is here:

http://report.quicklisp.org/2015-12-08/failure-report/cl-ana.html#cl-ana.plotting

**Comment by ghollisjr** [comment]
Replaced the compile time spawning with a smarter system, hopefully that fixes it.

**Comment by quicklisp** [comment]
Thanks, everything builds fine for me now!
